### ISSUE TITLE
Error occurs on running new_integrate.py

### ISSUE THREAD

**Issue by Russyz** [NHJohnson/pep-scripts#1]
Dr. Johnson,
Sorry to disturb you.When I run the new_integrate.py. I find there is no fold named pepin.

**Comment by NHJohnson** [comment]
Hello, 
This script is meant to run in the context of a copy of the Planetary Ephemeris Program, which I do not provide. The PEP directory structure includes the directory `pepin`.

**Comment by Russyz** [comment]
> Hello,
> This script is meant to run in the context of a copy of the Planetary Ephemeris Program, which I do not provide. The PEP directory structure includes the directory `pepin`.

Yeah, I know. The PEP can be get from https://github.com/jbattat/pep_core. But with no pepin there.

**Comment by NHJohnson** [comment]
The `pepin` directory can be created parallel to bigtest, peputil, etc. To work with this script, however, it would have to contain a set of initial condition files, which do not seem to be provided by that pep_core repo, at least not at this point.

**Comment by Russyz** [comment]
Could you please give me the the directory pepin which was described detailed on you PhD thesis?
Or can I have your social media ID so that I can ask you some questions?
